# Generated by Django 4.2.29 on 2026-03-06 06:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(help_text='Short AI-generated or extracted summary.')),
                ('content', models.TextField(help_text='Full article body (HTML allowed).')),
                ('original_url', models.URLField(blank=True, default='', max_length=700)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('images', models.JSONField(blank=True, default=list, help_text='JSON list of image URLs, e.g. ["https://…/a.jpg", "https://…/b.jpg"]')),
                ('ai_verdict', models.CharField(choices=[('REAL', 'Real'), ('FAKE', 'Fake'), ('UNCERTAIN', 'Uncertain')], default='UNCERTAIN', max_length=12)),
                ('confidence_score', models.FloatField(default=0, help_text='AI confidence 0–100.')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('is_breaking', models.BooleanField(default=False, help_text='Marked as breaking when: REAL + confidence > 90 + admin approved.')),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', help_text='Unique ID from the original source to prevent duplicates.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Set when article is approved.', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('twitter', 'X (Twitter)'), ('rss', 'RSS Feed'), ('website', 'Website')], max_length=10)),
                ('url', models.URLField(max_length=500)),
                ('logo', models.URLField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive sources are skipped during fetching.')),
                ('reliability_score', models.IntegerField(default=50, help_text='0–100 baseline trust score assigned by admin.')),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monitored Source',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verdict', models.CharField(choices=[('REAL', 'Real'), ('FAKE', 'Fake'), ('UNCERTAIN', 'Uncertain')], max_length=12)),
                ('confidence_score', models.FloatField(default=0)),
                ('explanation', models.TextField(blank=True, default='', help_text='AI-generated explanation of the verdict.')),
                ('provider', models.CharField(blank=True, default='', help_text='Which AI provider was used (mock / anthropic / openai).', max_length=50)),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Full raw AI response for debugging.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='news.newsarticle')),
            ],
            options={
                'verbose_name': 'Verification Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.source'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['status', '-created_at'], name='news_newsar_status_ca4bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['ai_verdict', '-confidence_score'], name='news_newsar_ai_verd_8f901b_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['is_breaking', '-published_at'], name='news_newsar_is_brea_f0378d_idx'),
        ),
    ]
