# Generated by Django 5.2.12 on 2026-03-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='key_points',
            field=models.JSONField(blank=True, default=list, help_text='AI-generated key points, e.g. ["point 1", "point 2", "point 3"]'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of image URLs.'),
        ),
        migrations.AlterField(
            model_name='verificationlog',
            name='provider',
            field=models.CharField(blank=True, default='', help_text='Which AI provider was used.', max_length=50),
        ),
    ]
