# Generated by Django 5.2.12 on 2026-03-20 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticle_key_points_alter_newsarticle_images_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Admin user who owns this source. Empty = shared/system source.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to=settings.AUTH_USER_MODEL),
        ),
    ]
