# Generated by Django 5.2.12 on 2026-03-20 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticle_key_points_alter_newsarticle_images_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='owners',
            field=models.ManyToManyField(blank=True, help_text='Admin users who can see this source. Empty = visible to all (shared).', related_name='sources', to=settings.AUTH_USER_MODEL),
        ),
    ]
